version: '3'
services:
  app:
    container_name: rest_api
    build: .
    ports:
      - "8282:8282"
    restart: on-failure
    volumes:
      - rest_api:/usr/src/app/
    depends_on:
      - db
    networks:
      - rest_net

  db:
    image: postgres
    container_name: rest_api_db
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - DATABASE_HOST=${POSTGRES_HOST}
    ports:
      - '5432:5432'
    volumes:
      - ./scripts/postgres/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - rest_net

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "lucas.silva.silveira@rede.ulbra.br"
      PGADMIN_DEFAULT_PASSWORD: "123456"
    ports:
      - "5454:80"
    depends_on:
      - db

volumes:
  rest_api:

networks:
  rest_net:

